# Faça um programa que leia algo no teclado e mostre todas suas informações #
a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas? ', a.islower())
print("Está capitalizada, ou seja, primeira letra em maiúscula?", a.istitle())
